# Develop override settings

url: http://localhost:4000

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
<<<<<<< HEAD
  style: expanded
=======
  style: expanded
>>>>>>> gh-pages
